# Generated by Django 3.0.8 on 2020-07-15 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='meal_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipe',
            name='ingredients',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='steps',
            field=models.TextField(max_length=2500),
        ),
    ]
