# Generated by Django 3.0.8 on 2020-07-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200715_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='img_src_1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='img_src_2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='receipe',
            name='img_src_3',
            field=models.URLField(blank=True),
        ),
    ]
